# Generated by Django 3.1 on 2020-11-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_text', models.CharField(max_length=500)),
                ('exam_text', models.CharField(max_length=500)),
                ('img_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HighHeels',
            fields=[
                ('is_visible', models.BooleanField(default=False)),
                ('is_examined', models.BooleanField(default=False)),
                ('sent_away_time', models.DateTimeField(null=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.itemmeta')),
            ],
        ),
        migrations.CreateModel(
            name='Knife',
            fields=[
                ('is_visible', models.BooleanField(default=False)),
                ('is_examined', models.BooleanField(default=False)),
                ('sent_away_time', models.DateTimeField(null=True)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.itemmeta')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('is_visible', models.BooleanField(default=False)),
                ('is_examined', models.BooleanField(default=False)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.itemmeta')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_questions', models.CharField(max_length=500)),
                ('high_heels', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.highheels')),
                ('knife', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.knife')),
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.phone')),
            ],
        ),
    ]
