# Generated by Django 3.1 on 2020-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201108_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='asked_questions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
