# Generated by Django 3.1 on 2020-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201108_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmeta',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
