# Generated by Django 3.1 on 2020-11-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201109_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='background_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
