# Generated by Django 3.1 on 2020-11-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201109_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
