# Generated by Django 3.1 on 2020-11-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_place_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('gets_unlocked', models.BooleanField(default=False)),
                ('video_title', models.CharField(max_length=100)),
                ('parentquestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.question')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.person')),
            ],
        ),
    ]
