# Generated by Django 3.1 on 2020-11-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_beginning',
            field=models.BooleanField(default=False),
        ),
    ]
