# Generated by Django 3.1 on 2020-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20201110_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='asked_questions',
        ),
        migrations.AddField(
            model_name='player',
            name='met_felix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='met_honey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='met_julian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='met_sophia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='met_stripper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='old_but_gold_visitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='park_visitable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='twoinone_visitable',
            field=models.BooleanField(default=False),
        ),
    ]
