# Generated by Django 3.1 on 2020-11-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20201110_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('is_visible', models.BooleanField(default=False)),
                ('is_examined', models.BooleanField(default=False)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.itemmeta')),
            ],
        ),
        migrations.RemoveField(
            model_name='knife',
            name='data',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='data',
        ),
        migrations.RemoveField(
            model_name='player',
            name='high_heels',
        ),
        migrations.RemoveField(
            model_name='player',
            name='knife',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone',
        ),
        migrations.DeleteModel(
            name='HighHeels',
        ),
        migrations.DeleteModel(
            name='Knife',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AddField(
            model_name='item',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
