# Generated by Django 3.1 on 2020-11-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20201111_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sent_away_time',
            field=models.DateTimeField(null=True),
        ),
    ]
