# Generated by Django 3.1 on 2020-11-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_item_sent_away_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
