# Generated by Django 3.1 on 2020-11-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20201111_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='causedevent',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='askedquestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.question'),
        ),
    ]
