# Generated by Django 3.1 on 2020-11-12 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20201112_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='parentquestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_question', to='game.question'),
        ),
    ]
