# Generated by Django 3.1 on 2020-11-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20201114_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectortext',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspectortext',
            name='text',
            field=models.CharField(max_length=400),
        ),
    ]
