# Generated by Django 3.1 on 2020-11-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_auto_20201114_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectortext',
            name='parenttext',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_text', to='game.inspectortext'),
        ),
        migrations.AlterField(
            model_name='inspectortext',
            name='on_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='causes_inspector', to='game.event'),
        ),
    ]
