# Generated by Django 3.1 on 2020-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20201114_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trigger',
            field=models.BooleanField(default=False),
        ),
    ]
