# Generated by Django 3.1 on 2020-11-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_event_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectortext',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
