# Generated by Django 3.1 on 2020-11-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_auto_20201114_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectortext',
            name='finishes_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finished_by_inspector', to='game.event'),
        ),
    ]
