# Generated by Django 3.1 on 2020-11-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_inspectortext_finishes_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cafe_visitable',
            field=models.BooleanField(default=False),
        ),
    ]
