# Generated by Django 3.1 on 2020-11-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_auto_20201114_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectortext',
            old_name='HTMLValue',
            new_name='ButtonValue',
        ),
    ]
