# Generated by Django 3.1 on 2020-11-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_auto_20201114_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.itemmeta'),
        ),
    ]
