# Generated by Django 3.1 on 2020-11-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_auto_20201115_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInterrupt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_time', models.FloatField()),
                ('resume_time', models.FloatField()),
                ('unique_id', models.CharField(blank=True, max_length=30, null=True)),
                ('inspector_text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.inspectortext')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.question')),
            ],
        ),
    ]
