# Generated by Django 3.1 on 2020-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_questioninterrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectortext',
            name='submit_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
