# Generated by Django 3.1 on 2020-11-17 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_inspectortext_submit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_id', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
    ]
