# Generated by Django 3.1.3 on 2020-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_intermediatestand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
