# Generated by Django 3.1.3 on 2020-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_auto_20201118_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='trigger',
        ),
        migrations.AddField(
            model_name='player',
            name='final_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
